(()=>{"use strict";function boot(){const root=document.querySelector("#authScreen.auth-v14 .hs-register");if(!root){setTimeout(boot,250);return}if(root.dataset.v15)return;root.dataset.v15="1";
const ids=["v13Name","v13Efootball","v13Whatsapp","v13Time","v13Prior","v13Commit","v13Rules","v13Email","v13Password"];
const groups=[["المعلومات الأساسية",["v13Name","v13Efootball","v13Whatsapp"]],["اختيارات البطولة",["v13Time","v13Prior"]],["الالتزام بالقوانين",["v13Commit","v13Rules"]],["إنشاء الحساب",["v13Email","v13Password"]]];
const step=document.createElement("div");step.className="v15-steps";step.innerHTML=groups.map((g,i)=>'<button type="button" data-step="'+i+'"><b>'+(i+1)+'</b><span>'+g[0]+"</span></button>").join("");root.prepend(step);
const controls=document.createElement("div");controls.className="v15-controls";controls.innerHTML='<button type="button" class="v15-prev">رجوع</button><button type="button" class="v15-next">التالي</button>';root.insertBefore(controls,document.getElementById("v13Register"));
function field(id){const e=document.getElementById(id);if(!e)return[];const a=[e,e.previousElementSibling];if(e.parentElement&&e.parentElement!==root)a.push(e.parentElement);return a}
function setDisplay(el,on){field(el).forEach(x=>{if(x&&x.classList?.contains("hs-check"))x.style.display=on?"":"none";else if(x&&x.tagName!=="INPUT"&&x.tagName!=="SELECT")x.style.display=on?"":"none"});const e=document.getElementById(el);if(e)e.style.display=on?"":"none";const l=e?.previousElementSibling;if(l?.classList.contains("hs-label"))l.style.display=on?"":"none"}
function go(n){n=Math.max(0,Math.min(3,n));ids.forEach(id=>setDisplay(id,false));groups[n][1].forEach(id=>setDisplay(id,true));document.querySelectorAll(".hs-choice,.hs-two,.hs-row-choice").forEach(x=>x.style.display=n===1?"":"none");document.querySelectorAll(".v15-steps button").forEach((b,i)=>b.classList.toggle("active",i===n));controls.style.display=n===3?"none":"flex";document.getElementById("v13Register").style.display=n===3?"":"none";controls.dataset.step=n}
function valid(n){if(n===0)return ["v13Name","v13Efootball","v13Whatsapp"].every(id=>document.getElementById(id)?.value.trim());if(n===2)return document.getElementById("v13Commit")?.checked&&document.getElementById("v13Rules")?.checked;return true}
let n=0;go(n);controls.querySelector(".v15-next").onclick=()=>{if(!valid(n)){const m=document.getElementById("authMessage");if(m){m.textContent="عمر المعلومات المطلوبة قبل ما تكمل.";m.className="hs-message error"}return}go(++n)};controls.querySelector(".v15-prev").onclick=()=>go(--n);
document.querySelectorAll(".v15-steps button").forEach(b=>b.onclick=()=>{const x=+b.dataset.step;if(x<=n)go(x)});
}boot()})();