const state={world:null,day:1,xp:0,credits:500,history:[]};
const worlds={football:{title:"PRO CAREER",desc:"بدا من الصفر وبني مسيرتك الكروية.",start:"أول فرصة جاتك: أكاديمية صغيرة باغية تجربك. عندك يوم واحد باش تقرر كيفاش تبدا.",choices:[["تدخل الأكاديمية","طريق آمن، ولكن المنافسة قوية."],["تتدرب بوحدك","حرية أكبر، لكن ما عندك حتى ضمان."],["تقلب على فريق أكبر","مخاطرة كبيرة وقد تحصل على فرصة استثنائية."]]},business:{title:"ZERO TO COMPANY",desc:"بدا بـ500€ وحاول تبني مشروع حقيقي.",start:"عندك 500€ فقط، وفكرة صغيرة. أول قرار غادي يحدد واش غادي تحافظ على فلوسك ولا تغامر.",choices:[["تطلق نسخة بسيطة","تختبر الفكرة قبل ما تصرف بزاف."],["تستثمر أغلب الميزانية","ممكن تكبر بسرعة، وممكن تخسر."],["تقلب على شريك","كتربح خبرة وموارد ولكن كتشارك القرار."]]},survival:{title:"LAST CITY",desc:"مدينة مجهولة، موارد قليلة، وكل قرار كيبدل القصة.",start:"كتفيق فمدينة خاوية. معاك حقيبة صغيرة، بطارية محدودة، وثلاثة طرق قدامك.",choices:[["تمشي للمدينة","ممكن تلقى ناس أو خطر."],["تمشي للجبال","مكان هادئ ولكن بعيد على الموارد."],["تبقى فالمكان","كتجمع معلومات قبل المخاطرة."]]}};
function $(s){return document.querySelector(s)}
function renderWorld(){const w=worlds[state.world];$("#worldTitle").textContent=w.title;$("#worldDesc").textContent=w.desc;$("#day").textContent="DAY "+state.day;$("#xp").textContent=state.xp+" XP";$("#credits").textContent=state.credits+" C";$("#sceneTitle").textContent=state.day===1?w.start:"القرار اللي فات بدّل العالم ديالك.";
$("#sceneText").textContent=state.day===1?"اختار قرار واحد. ما كاينش اختيار مثالي؛ كل طريق عندو ثمن ونتيجة.":state.history.at(-1);
$("#choices").innerHTML=w.choices.map((c,i)=>'<button class="choice" data-i="'+i+'"><b>'+c[0]+'</b><span>'+c[1]+'</span></button>').join("");
document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>choose(+b.dataset.i));$("#world").classList.add("active");$("#home").style.display="none"}
function choose(i){const w=worlds[state.world];const c=w.choices[i];state.history.push("اخترت: "+c[0]);state.day++;state.xp+=25;state.credits+=i===2?-100:50;localStorage.setItem("chaouiX",JSON.stringify(state));if(state.day>6){$("#sceneTitle").textContent="🎉 الفصل الأول سالا";$("#sceneText").textContent="وصلتي لنهاية أول فصل. العالم ديالك دابا عندو تاريخ، وقراراتك الجاية غادي تبني الفصل الثاني.";$("#choices").innerHTML='<button class="choice" id="continue"><b>نكمل القصة</b><span>نبدا فصل جديد بنفس الشخصية.</span></button>';$("#continue").onclick=()=>{state.day=1;state.history=[];renderWorld()};return}renderWorld()}
document.querySelectorAll(".mode").forEach(x=>x.onclick=()=>{state.world=x.dataset.world;state.day=1;state.xp=0;state.credits=500;state.history=[];renderWorld()});
$("#back").onclick=()=>{$("#world").classList.remove("active");$("#home").style.display="block"};
$("#reset").onclick=()=>{localStorage.removeItem("chaouiX");location.reload()};
try{Object.assign(state,JSON.parse(localStorage.getItem("chaouiX")||"{}"))}catch(e){}