/* CHAoui Owner HQ V15 */
(()=>{"use strict";let boot=false,tab="overview";const $=id=>document.getElementById(id);const esc=v=>window.escapeHTML?window.escapeHTML(v??""):String(v??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));const tabs=[["overview","👑 التحكم الكامل"],["command","🎯 مركز القيادة"],["players","👥 اللاعبون"],["matches","⚔️ المباريات والدورات"],["activity","◷ مراقبة النشاط"],["subs","🔄 البدلاء"],["codes","🔐 استرجاع الأكواد"],["deleted","🗑️ المحذوفون"],["settings","⚙️ إعدادات البطولة"],["assistant","✦ المساعد الذكي"],["contact","💬 إدارة التواصل"],["ads","📢 الإعلانات"],["issues","⚠️ المشكلات"],["xp","⚡ XP المباريات"],["shop","🛒 نقاط المتجر"],["names","📝 طلبات الأسماء"],["maintenance","🛠️ الصيانة"],["updates","🆕 آخر تحديث"]];
let cache={players:[],tournaments:[],matches:[],complaints:[],requests:[],activity:[],settings:null};
function ok(){return window.currentProfile?.role==="owner"}async function load(){if(!ok())return;const [p,t,m,c,r,a,s]=await Promise.all([supabaseClient.from("profiles").select("*").order("created_at",{ascending:false}).limit(100),supabaseClient.from("tournaments").select("*").order("created_at",{ascending:false}).limit(100),supabaseClient.from("matches").select("*").order("scheduled_at",{ascending:false}).limit(100),supabaseClient.from("complaints").select("*").order("created_at",{ascending:false}).limit(50),supabaseClient.from("organizer_subscription_requests").select("*").order("requested_at",{ascending:false}).limit(50),supabaseClient.from("activity_feed").select("*").order("created_at",{ascending:false}).limit(30),supabaseClient.from("app_settings").select("*").eq("id",1).maybeSingle()]);cache={players:p.data||[],tournaments:t.data||[],matches:m.data||[],complaints:c.data||[],requests:r.data||[],activity:a.data||[],settings:s.data||null};render()}
function shell(){const root=$("king")||$("organizer");if(!root)return;root.className="page chaoui-owner-v15";root.innerHTML='<header class="o15-top"><div class="o15-brand"><div class="o15-logo">🏆</div><div><b>لوحة المنظم</b><small>CHAoui PRO · eFootball 1VS1</small></div></div><div class="o15-search">⌕ &nbsp; بحث عن لاعب أو بطولة...</div><button class="o15-logout" id="o15Logout">↪ خروج</button></header><nav class="o15-nav" id="o15Nav"></nav><div class="o15-wrap"><section class="o15-hero"><div><span style="color:#b88b25;font-size:9px">OWNER COMMAND CENTER</span><h1 id="o15Title">التحكم الكامل 👑</h1><p>كل العمليات المهمة ديال CHAoui من مكان واحد — <strong>Mobile + PC</strong>.</p></div><strong>OWNER</strong></section><div id="o15Body"></div></div>';$("o15Logout").onclick=()=>window.logoutUser?.()}
function renderNav(){$("o15Nav").innerHTML=tabs.map((x,i)=>'<button class="'+(tab===x[0]?"active":"")+'" data-o15="'+x[0]+'">'+x[1]+"</button>").join("");$("o15Nav").querySelectorAll("button").forEach(b=>b.onclick=()=>{tab=b.dataset.o15;render()})}
function stats(){const live=cache.tournaments.filter(x=>x.status==="live").length,open=cache.tournaments.filter(x=>x.status==="open").length,pending=cache.matches.filter(x=>["scheduled","result_submitted"].includes(x.status)).length,issues=cache.complaints.filter(x=>!["resolved","closed"].includes(x.status)).length;return '<div class="o15-stats">'+[["اللاعبون",cache.players.length],["البطولات",cache.tournaments.length],["مباشرة",live],["مفتوحة",open],["مباريات نشيطة",pending],["مشكلات مفتوحة",issues]].map(x=>'<div class="o15-stat"><span>'+x[0]+'</span><b>'+x[1]+"</b></div>").join("")+"</div>"}
function row(title,meta,action){return'<div class="o15-row"><div><b>'+esc(title)+'</b><small>'+esc(meta||"")+"</small></div>"+(action||"")+"</div>"}
function view(){const t=cache.tournaments.slice(0,6);if(tab==="overview")return stats()+'<div class="o15-grid"><article class="o15-card"><h2>⚡ يحتاج تدخل دابا</h2><div class="o15-list">'+row("نتائج تنتظر التأكيد",cache.matches.filter(x=>["scheduled","result_submitted"].includes(x.status)).length+' مباراة','<button class="o15-btn gold" data-o15tab="matches">فتح</button>')+row("تسجيلات / طلبات",cache.requests.length+" طلب",' <button class="o15-btn" data-o15tab="players">فتح</button>')+row("مشاكل مفتوحة",cache.complaints.length+" شكاية",'<button class="o15-btn red" data-o15tab="issues">فتح</button>')+"</div></article><article class="o15-card"><h2>🏆 آخر البطولات</h2><div class="o15-list">"+(t.map(x=>row(x.name,x.status+" · "+(x.current_players||0)+"/"+(x.capacity||0),'<button class="o15-btn" data-open="'+x.id+'">فتح</button>')).join("")||'<div class="o15-empty">ما كايناش بطولات.</div>')+"</div></article></div>";
if(tab==="command")return stats()+'<div class="o15-card"><h2>🎯 مركز القيادة</h2><div class="o15-list">'+row("إنشاء بطولة","بداية دورة جديدة",'<button class="o15-btn gold" id="o15Create">+ إنشاء</button>')+row("إدارة اللاعبين","قبول، Premium، Coins، Organizer",'<button class="o15-btn" data-o15tab="players">فتح</button>')+row("المباريات والنتائج","تأكيد، Match Room، مشاكل",'<button class="o15-btn" data-o15tab="matches">فتح</button>')+row("الصيانة","قفل/فتح الوصول",'<button class="o15-btn" data-o15tab="maintenance">فتح</button>')+"</div></div>";
if(tab==="players"){return '<div class="o15-card"><h2>👥 اللاعبون</h2><div class="o15-list">'+(cache.players.slice(0,60).map(p=>row(p.display_name||p.username,(p.player_code||"بدون كود")+" · "+(p.role||"player")+" · Rating "+(p.rating||0),'<button class="o15-btn" data-player="'+p.id+'">إدارة</button>')).join("")||'<div class="o15-empty">لاعبين مازال ما كاينينش.</div>')+"</div></div>"}
if(tab==="matches"){return '<div class="o15-card"><h2>⚔️ المباريات والدورات</h2><div class="o15-list">'+(cache.matches.slice(0,50).map(m=>row(m.round||"Match",m.status||"—",'<button class="o15-btn" data-match="'+m.id+'">فتح Match Room</button>')).join("")||'<div class="o15-empty">ما كايناش مباريات مسجلة دابا.</div>')+"</div></div><div class="o15-card"><h2>🏆 البطولات</h2><div class="o15-list">"+(cache.tournaments.map(t=>row(t.name,t.status+" · "+(t.format||"eFootball"),'<button class="o15-btn" data-open="'+t.id+'">فتح</button>')).join("")||'<div class="o15-empty">لا بطولات.</div>')+"</div></div>"}
if(tab==="activity")return '<div class="o15-card"><h2>◷ مراقبة النشاط</h2><div class="o15-list">'+(cache.activity.map(a=>row(a.title||a.type,a.body||"",'<small>'+esc(a.created_at||"")+"</small>")).join("")||'<div class="o15-empty">ما كاين حتى نشاط مسجل.</div>')+"</div></div>";
if(tab==="subs")return '<div class="o15-card"><h2>🔄 البدلاء</h2><p style="color:#807467;font-size:10px">البدلاء خاصهم يبقاو تحت مراقبة Owner باش ما يتبدل حتى لاعب بلا أثر.</p><div class="o15-list">'+(cache.players.filter(p=>p.role==="player").slice(0,30).map(p=>row(p.display_name||p.username,"Player · "+(p.rating||0)+" Rating",'<button class="o15-btn" data-player="'+p.id+'">تعيين/إدارة</button>')).join("")||'<div class="o15-empty">ما كاين حتى لاعب متاح دابا.</div>')+"</div></div>";
if(tab==="codes")return '<div class="o15-card"><h2>🔐 أكواد اللاعبين</h2><div class="o15-list">'+(cache.players.map(p=>row(p.display_name||p.username,p.player_code||"ما عندوش كود",'<button class="o15-btn" data-copy="'+esc(p.player_code||"")+'">نسخ</button>')).join("")||'<div class="o15-empty">ما كايناش أكواد.</div>')+"</div></div>";
if(tab==="deleted")return '<div class="o15-card"><h2>🗑️ المحذوفون</h2><p style="color:#807467;font-size:10px">هاد القسم غادي يعرض غير السجلات اللي كاينة فعلاً فقاعدة البيانات. ما غاديش نفترض column للحذف ما كايناش.</p><div class="o15-empty">ما كايناش بيانات حذف مؤكدة فالمخطط الحالي.</div></div>";
if(tab==="settings")return '<div class="o15-card"><h2>⚙️ إعدادات البطولة</h2><div class="o15-list">'+row("التسجيل",cache.settings?.registration_enabled?"🟢 مفتوح":"🔴 مغلق")+row("الانضمام",""+(cache.settings?.join_enabled?"🟢 مفتوح":"🔴 مغلق"))+row("الصيانة",cache.settings?.maintenance?"🔴 مفعلة":"🟢 غير مفعلة")+'</div></div>';
if(tab==="assistant")return '<div class="o15-card"><h2>✦ المساعد الذكي</h2><p style="color:#9a8d7d">مساعد Owner يركز على حالة البطولات والمباريات والمشاكل.</p><button class="o15-btn gold" data-page="assistant">فتح المساعد</button></div>';
if(tab==="contact")return '<div class="o15-card"><h2>💬 إدارة التواصل</h2><div class="o15-list">'+row("الرسائل","فتح Messenger",'<button class="o15-btn" data-page="chat">فتح</button>')+row("الشكايات","مركز الدعم",'<button class="o15-btn" data-page="complaints">فتح</button>')+"</div></div>";
if(tab==="ads")return '<div class="o15-card"><h2>📢 الإعلانات</h2><p style="color:#9a8d7d">الإعلانات الحالية تدار من محتوى المنصة. افتح مركز التواصل لإرسال إعلان للاعبين.</p><button class="o15-btn gold" data-o15tab="contact">إدارة التواصل</button></div>';
if(tab==="issues")return '<div class="o15-card"><h2>⚠️ المشكلات</h2><div class="o15-list">'+(cache.complaints.map(c=>row(c.subject||c.title||"شكاية",c.status||"مفتوحة",'<button class="o15-btn red" data-page="complaints">فتح</button>')).join("")||'<div class="o15-empty">ما كايناش شكايات.</div>')+"</div></div>";
if(tab==="xp")return '<div class="o15-card"><h2>⚡ XP المباريات</h2><p style="color:#9a8d7d">الـXP الحالي كيبقى مرتبط بسجل التقدم الموجود فالنظام.</p><button class="o15-btn gold" data-page="progression">فتح التقدم</button></div>";
if(tab==="shop")return '<div class="o15-card"><h2>🛒 نقاط المتجر</h2><p style="color:#9a8d7d">إدارة Coins والجوائز والصناديق كتفتح من الاقتصاد الحالي.</p><button class="o15-btn gold" data-action="shop">فتح الاقتصاد</button></div>';
if(tab==="names")return '<div class="o15-card"><h2>📝 طلبات الأسماء</h2><div class="o15-list">'+(cache.requests.map(r=>row(r.id||"طلب",r.status||"pending",'<button class="o15-btn" data-page="organizer">مراجعة</button>')).join("")||'<div class="o15-empty">ما كايناش طلبات.</div>')+"</div></div>";
if(tab==="maintenance")return '<div class="o15-card"><h2>🛠️ الصيانة</h2><div class="o15-list">'+row("حالة المنصة",cache.settings?.maintenance?"🔴 صيانة":"🟢 التطبيق مفتوح",'<button class="o15-btn red" data-maint>فتح مركز الصيانة</button>')+row("التسجيل",cache.settings?.registration_enabled?"🟢 مفتوح":"🔴 مغلق")+row("الانضمام",cache.settings?.join_enabled?"🟢 مفتوح":"🔴 مغلق")+"</div></div>";
return '<div class="o15-card"><h2>🆕 آخر تحديث</h2><p style="color:#9a8d7d">CHAoui UX V15 — Player / Owner / Auth redesign. الواجهة الجديدة مبنية Mobile First وكتحافظ على وظائف Supabase الحالية.</p><span style="color:#f5c451">V15 · 26/09/2026</span></div>'}
function render(){if(!ok()){tab="overview";return}if(!( $("king")||$("organizer"))?.classList.contains("chaoui-owner-v15"))shell();renderNav();$("o15Title").textContent=tabs.find(x=>x[0]===tab)?.[1].replace(/^[^ ]+ /,"")||"التحكم الكامل";$("o15Body").innerHTML=view();bind()}
function bind(){$("o15Body")?.querySelectorAll("[data-o15tab]").forEach(b=>b.onclick=()=>{tab=b.dataset.o15tab;render()});$("o15Body")?.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>window.showPage?.(b.dataset.page));$("o15Create")?.addEventListener("click",()=>window.openCreateTournament?.());$("o15Body")?.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>window.openTournament?.(b.dataset.open));$("o15Body")?.querySelectorAll("[data-copy]").forEach(b=>b.onclick=()=>navigator.clipboard?.writeText(b.dataset.copy||"").then(()=>window.showToast?.("تم نسخ الكود 📋")));$("o15Body")?.querySelectorAll("[data-match]").forEach(b=>b.onclick=()=>window.openMatchRoom?.(b.dataset.match));$("o15Body")?.querySelectorAll("[data-player]").forEach(b=>b.onclick=()=>window.showToast?.("مركز إدارة اللاعب غادي يتوسع مع الصلاحيات الحالية."));$("o15Body")?.querySelector("[data-action=shop]")?.addEventListener("click",()=>window.showPage?.("wallet"));$("o15Body")?.querySelector("[data-maint]")?.addEventListener("click",()=>window.showPage?.("settings"))}
function boot(){if(boot)return;if($("king")&&window.currentProfile){boot=true;const old=window.showPage;window.showPage=function(page,...args){const r=old?.call(this,page,...args);if((page==="king"||page==="organizer")&&window.currentProfile?.role==="owner"){setTimeout(()=>{if(page==="organizer") tab="overview"; load()},40)}return r};if(window.currentProfile.role==="owner")setTimeout(load,100)}else setTimeout(boot,350)}boot();
})();