/* CHAoui Player V15 */
(()=>{"use strict";let ready=false;
const $=id=>document.getElementById(id);
const esc=v=>window.escapeHTML?window.escapeHTML(v??""):String(v??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
function nav(){if($("p15Top"))return;
 document.body.classList.add("chaoui-player-v15");
 const app=$("app"); if(!app)return;
 const top=document.createElement("header");top.id="p15Top";top.className="p15-top";top.innerHTML='<div class="p15-brand"><img src="logo.png"><div><b>CHAoui PRO</b><small>eFOOTBALL TOURNAMENT</small></div></div><div class="p15-head-actions"><button data-page="notifications">♢</button><button data-page="profile">♙</button></div>';
 app.prepend(top);
 const bottom=document.createElement("nav");bottom.className="p15-bottom";bottom.innerHTML='<button data-page="home"><i>⌂</i><b>الرئيسية</b></button><button data-page="tournaments"><i>♜</i><b>البطولة</b></button><button data-page="profile"><i>♙</i><b>حسابي</b></button><button data-page="more"><i>☰</i><b>المزيد</b></button>';app.append(bottom);
 bottom.querySelectorAll("button").forEach(b=>b.onclick=()=>window.showPage?.(b.dataset.page));
 top.querySelectorAll("button").forEach(b=>b.onclick=()=>window.showPage?.(b.dataset.page));
}
function home(){const page=$("home");if(!page||page.dataset.p15)return;page.dataset.p15="1";
 const legacy=[...page.children];legacy.forEach(x=>{if(!x.classList.contains("home-legacy-hooks"))x.style.display="none"});
 const wrap=document.createElement("div");wrap.className="p15-home";wrap.innerHTML='<div class="p15-page-head"><span class="p15-kicker">PLAYER HOME</span><h1>الرئيسية</h1><p>كل ما تحتاجو باش تعرف شنو واقع دابا.</p></div><section class="p15-hero"><div><span class="p15-kicker">CHAoui PLAYER</span><h2 id="p15Name">Player</h2><p id="p15Handle">@player</p><div class="p15-rating">⭐ <span id="p15Rating">0</span> Rating · LV.<span id="p15Level">1</span></div></div><div id="p15Avatar" class="p15-avatar">C</div></section><section class="p15-section"><div class="p15-section-head"><h3>⚡ المباراة القادمة</h3><span>NEXT MATCH</span></div><div class="p15-next"><div class="vs"><strong id="p15Me">أنت</strong><em>VS</em><strong id="p15Opp">المنافس</strong></div><button class="p15-action" data-page="matches">فتح مبارياتي</button></div></section><section class="p15-section"><div class="p15-section-head"><h3>📊 أرقامك</h3><span>CAREER</span></div><div class="p15-stats"><div class="p15-stat"><span>المباريات</span><b id="p15Matches">0</b></div><div class="p15-stat"><span>الفوز</span><b id="p15Wins">0</b></div><div class="p15-stat"><span>Win Rate</span><b id="p15Winrate">0%</b></div><div class="p15-stat"><span>Points</span><b id="p15Points">0</b></div></div></section><section class="p15-section"><div class="p15-section-head"><h3>📰 آخر الأخبار</h3><span>3 MAX</span></div><div class="p15-news"><article><b>🏆 تابع البطولات ديالك</b><span>دخل للبطولة باش تشوف المجموعة، الترتيب والمباريات.</span></article><article><b>⚡ النتيجة كتأثر على الترتيب</b><span>أكد النتيجة ديالك بعد كل Match Room.</span></article><article><b>📢 أخبار المنظم</b><span>الإعلانات المهمة غادي تبان هنا.</span></article></div></section></div>';
 page.append(wrap);
}
function tournament(){const page=$("tournaments");if(!page||page.dataset.p15)return;page.dataset.p15="1";const wrap=document.createElement("div");wrap.className="p15-tournament-wrap";wrap.innerHTML='<div class="p15-page-head"><span class="p15-kicker">COMPETITION HUB</span><h1>البطولة</h1><p>كلشي متعلق بالمنافسة ديالك فبلاصة وحدة.</p></div><div class="p15-subtabs"><button class="active" data-panel="groups">👥 مجموعاتي</button><button data-panel="ranking">🏅 ترتيبي</button><button data-panel="achievements">🏆 إنجازاتي</button><button data-panel="stats">📊 إحصائياتي</button><button data-panel="matches">⚔️ مبارياتي</button></div><div id="p15TournamentPanel" class="p15-subpanel"><h3>👥 مجموعاتي</h3><p>اختار بطولة نشطة من اللائحة لتشوف المجموعة ديالك واللاعبين.</p></div>';
 page.prepend(wrap);
 wrap.querySelectorAll(".p15-subtabs button").forEach(b=>b.onclick=()=>panel(b.dataset.panel));
 function panel(type){const x=$("p15TournamentPanel");if(!x)return;const data={groups:["👥 مجموعاتي","شوف المجموعة واللاعبين ديال البطولة الحالية من تفاصيل البطولة."],ranking:["🏅 ترتيبي","التصنيف ديالك، النقاط، الفوز وWin Rate."],achievements:["🏆 إنجازاتي","الإنجازات والجوائز المرتبطة بالموسم والبطولات."],stats:["📊 إحصائياتي","المباريات، الفوز، الخسارة، Rating وForm ديالك."],matches:["⚔️ مبارياتي","المباريات القادمة والنتائج السابقة ديالك."]}[type];x.innerHTML='<h3>'+data[0]+'</h3><p>'+data[1]+'</p><button class="p15-action" data-page="'+(type==="matches"?"matches":type==="ranking"?"ranking":type==="achievements"?"progression":"tournaments")+'">فتح القسم</button>';x.querySelector("button").onclick=()=>window.showPage?.(x.querySelector("button").dataset.page)}
}
function account(){const page=$("profile");if(!page||page.dataset.p15Account)return;page.dataset.p15Account="1";const legacy=[...page.children];legacy.forEach(x=>{if(!x.classList.contains("player-legacy-hooks"))x.style.display="none"});const wrap=document.createElement("div");wrap.className="p15-account";wrap.innerHTML='<div class="p15-page-head"><span class="p15-kicker">PLAYER ACCOUNT</span><h1>حسابي</h1><p>الهوية، الإعدادات والخصوصية ديالك.</p></div><section class="p15-profile-card"><div class="p15-profile-top"><div id="p15ProfileAvatar" class="p15-profile-avatar">C</div><div><h2 id="p15AccountName">Player</h2><p id="p15AccountHandle">@player</p></div></div><div class="p15-profile-grid"><div><span>Rating</span><b id="p15AccountRating">0</b></div><div><span>Level</span><b id="p15AccountLevel">1</b></div><div><span>Points</span><b id="p15AccountPoints">0</b></div></div></section><div class="p15-settings"><button data-page="settings">⚙️ إعدادات الحساب<small>الحالة، الأمان والخروج</small></button><button data-page="premium">💎 Premium<small>المزايا الخاصة</small></button><button data-page="search">👥 الأصدقاء والبحث<small>قلب على لاعبين</small></button><button data-page="complaints">🚨 إبلاغ عن مشكلة<small>مركز الشكايات</small></button><button data-page="security">🔐 الخصوصية والأمان<small>حماية الحساب</small></button><button data-page="notifications">🔔 الإشعارات<small>آخر التنبيهات</small></button></div></div>';page.append(wrap);wrap.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>window.showPage?.(b.dataset.page))}
function chat(){const p=$("chat");if(p&&!p.dataset.p15){p.dataset.p15="1";p.classList.add("p15-chat")}}
function more(){const p=$("more");if(p&&!p.dataset.p15){p.dataset.p15="1";p.querySelector(".more-v8-title h1")?.replaceWith(Object.assign(document.createElement("h1"),{textContent:"المزيد"}))}}
function sync(){if(!window.currentProfile)return;const p=window.currentProfile,n=p.display_name||p.username||"CHAoui Player",rating=Number(p.rating||0),level=Number(p.level||1),wins=Number(p.wins||0),points=Number(p.points||0),matches=wins+Number(p.losses||0)+Number(p.draws||0),wr=matches?Math.round(wins/matches*100):0;["p15Name","p15AccountName"].forEach(id=>$(id)&&( $(id).textContent=n));["p15Handle","p15AccountHandle"].forEach(id=>$(id)&&($(id).textContent="@"+(p.username||"chaoui_player")));["p15Rating","p15AccountRating"].forEach(id=>$(id)&&($(id).textContent=rating));["p15Level","p15AccountLevel"].forEach(id=>$(id)&&($(id).textContent=level));$("p15Wins")&&($("p15Wins").textContent=wins);$("p15Points")&&($("p15Points").textContent=points);$("p15Matches")&&($("p15Matches").textContent=matches);$("p15Winrate")&&($("p15Winrate").textContent=wr+"%");const letter=String(n).trim().slice(0,1).toUpperCase()||"C";["p15Avatar","p15ProfileAvatar"].forEach(id=>$(id)&&($(id).textContent=letter))}
function hook(){if(ready)return;ready=true;nav();home();tournament();account();chat();more();sync();const old=window.showPage;window.showPage=function(page,...args){const r=old?.call(this,page,...args);setTimeout(()=>{sync();document.querySelectorAll(".p15-bottom button").forEach(b=>b.classList.toggle("active",b.dataset.page===page));if(page==="home")home();if(page==="tournaments")tournament();if(page==="profile")account();if(page==="chat")chat()},40);return r};setInterval(sync,1200)}
function boot(){if(ready)return;if($("app")&&window.currentProfile){hook()}else setTimeout(boot,350)}boot();
})();